version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tutor_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@123
      POSTGRES_DB: tutor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: tutor_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Pass@123@db:5432/tutor
      - SECRET_KEY=thisisasecretkey1234567890qwertyuiopasdfghjkl
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tutor_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
